require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

inhibit_all_warnings!

target 'Car' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  
  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'




  pod 'react-native-restart', :path => '../node_modules/react-native-restart'


  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  target 'CarTests' do
    inherit! :complete
    # Pods for testing
  end

  def min_OSTarget_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if Gem::Version.new('12.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.6.9', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.4.3' })
  post_install do |installer|
    flipper_post_install(installer)
    min_OSTarget_post_install(installer)
  end
end

target 'Car-tvOS' do
  # Pods for Car-tvOS

  target 'Car-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
