export const NUMBER_OF_MESSAGES_BELOW_FOCUSED = 5;
export const NUMBER_OF_NEW_MESSAGES = 51;
export const MILLISECONDS = 600;
export const OFFSET_TO_LOAD_NEW_MESSAGES = 100;
export const INITIAL_NUMBER_TO_RENDER = 60;