require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

inhibit_all_warnings!

target 'SoftServeCarMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  
  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'SoftServeCarMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  def min_OSTarget_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if Gem::Version.new('12.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    min_OSTarget_post_install(installer)
  end
end

target 'SoftServeCarMobile-tvOS' do
  # Pods for SoftServeCarMobile-tvOS

  target 'SoftServeCarMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
